/**
 * Boot-time migration runner for Rido.
 *
 * Idempotent: safe to call on every cold start. Internally it uses
 * drizzle-orm's `migrate()` which tracks applied migrations in the
 * `__drizzle_migrations` table; already-applied migrations are no-ops.
 *
 * Usage (from an instrumentation hook or a one-off script):
 *
 *   import { runMigrations } from "@/lib/db/migrations-runner";
 *   await runMigrations();
 *
 * The migration SQL lives in the `drizzle/` directory at the project root
 * and is generated by `drizzle-kit generate` (configured by drizzle.config.ts).
 */

import { migrate } from "drizzle-orm/postgres-js/migrator";
import { resolve } from "node:path";

import { getDb, closeDb, type Db } from "@/lib/db/client";
import { getEnv } from "@/lib/contract";

type RunMigrationsOptions = {
  /** Override the migrations folder. Defaults to <repo>/drizzle. */
  migrationsFolder?: string;
  /**
   * Reuse an existing Drizzle instance (e.g. in tests). When omitted a new
   * client is opened and closed for the migration pass.
   */
  db?: Db;
};

let migrationPromise: Promise<void> | null = null;

/**
 * Apply pending Drizzle migrations.
 *
 * Concurrent calls (e.g. multiple serverless invocations warming up at once)
 * share a single in-flight promise so we don't try to run two migration
 * passes in parallel.
 */
export function runMigrations(opts: RunMigrationsOptions = {}): Promise<void> {
  if (migrationPromise) return migrationPromise;

  migrationPromise = (async () => {
    // Touch the env once so misconfiguration fails loudly before we open a
    // connection to the database.
    getEnv();

    const ownClient = !opts.db;
    const db = opts.db ?? getDb();
    const folder = opts.migrationsFolder ?? resolve(process.cwd(), "drizzle");

    try {
      await migrate(db, { migrationsFolder: folder });
    } finally {
      if (ownClient) {
        // We opened the client for this run; hand it back so subsequent calls
        // re-establish lazily.
        await closeDb();
      }
    }
  })();

  // Reset the cached promise on rejection so the next boot can retry.
  migrationPromise.catch(() => {
    migrationPromise = null;
  });

  return migrationPromise;
}
