/**
 * In-memory job queue for Rido.
 *
 * This module is the process-local implementation of the background
 * job queue contract. A `JobQueue` is a FIFO store of jobs (each
 * identified by a UUID) drained by a worker pool of fixed
 * concurrency. Workers are registered per job name, failed jobs are
 * retried with exponential backoff, and jobs that exhaust their
 * retry budget are moved to a dead-letter array for inspection.
 *
 * ## Scope and limits
 *
 *   - **Process-local only.** State lives in module closures, so the
 *     queue is shared by every caller in the same Node process but
 *     *not* across instances. On Vercel that means "per warm serverless
 *     function". A future swap to a Redis- or Postgres-backed queue
 *     only needs to preserve the {@link JobQueue} interface — the
 *     {@link ./index} singleton will keep working.
 *   - **No persistence.** Jobs are lost on process restart. This is
 *     deliberate: the queue is meant for best-effort background work
 *     (sending transactional emails, refreshing cache entries,
 *     firing webhooks). For durable scheduling, use a managed
 *     scheduler or persist jobs to the database before submission.
 *   - **No distributed locking.** Because the store is in-memory and
 *     single-process, no two workers can race on the same job. A
 *     Redis-backed implementation will need an explicit lease/lock
 *     here.
 *   - **Backoff is `setTimeout`-based.** A pause that outlives the
 *     process is silently dropped. Acceptable for the in-memory
 *     backend; a durable implementation must persist `notBefore`
 *     and re-enqueue on boot.
 *
 * ## Failure model
 *
 * If the registered handler throws (or rejects, when the handler is
 * async), the queue:
 *
 *   1. Increments `job.attempts`.
 *   2. If `attempts < maxAttempts`, schedules a re-queue with a
 *      delay of `baseDelay * 2^(attempts - 1)` ms. This is the
 *      classic exponential backoff: 1s, 2s, 4s, 8s, … capped at
 *      `maxAttempts` total tries (so a job with `maxAttempts: 3`
 *      runs at t=0, t≈1s, t≈3s — three attempts total).
 *   3. If `attempts >= maxAttempts`, moves the job to the dead-letter
 *      array, fires the `onFailure` hook, and marks its status as
 *      `"dead"`.
 *
 * Successful runs fire the `onComplete` hook with the job's return
 * value, then drop the job from the live set (it is no longer
 * "queued" or "running", and a future `snapshot()` will not return
 * it).
 *
 * @module src/lib/queue/in-memory
 */

import { getLogger } from "@/lib/observability/logger";
import { getMetrics } from "@/lib/observability/metrics";

// ─── Public types ──────────────────────────────────────────────────────────

/**
 * The lifecycle status of a job. Stored on the job record and
 * returned by {@link JobQueue.submit}.
 *
 *   - `queued`   — waiting in the FIFO, never picked up.
 *   - `running`  — a worker is currently executing the handler.
 *   - `completed`— the handler returned without throwing. Set
 *                  transiently; the job is dropped from the live
 *                  store once the `onComplete` hook has been
 *                  notified, but the status is preserved on the
 *                  record for inspection through `getJob`.
 *   - `failed`   — an intermediate marker for a job that threw and
 *                  will be retried. Set while the backoff timer is
 *                  pending; the job becomes `queued` again when the
 *                  timer fires.
 *   - `dead`     — terminal. The job exhausted its retry budget and
 *                  has been moved to the dead-letter array.
 */
export type JobStatus =
  | "queued"
  | "running"
  | "completed"
  | "failed"
  | "dead";

/**
 * Per-job options accepted by {@link JobQueue.submit}. All fields are
 * optional; sensible defaults are supplied by the queue.
 */
export interface SubmitOptions {
  /**
   * Maximum number of *total* attempts before the job is moved to
   * the dead-letter array. The first attempt counts, so a
   * `maxAttempts: 3` job is run at most three times. Must be a
   * positive integer. Defaults to `3`.
   */
  maxAttempts?: number;
  /**
   * Base delay in milliseconds for the exponential backoff. The
   * delay before retry attempt `n` (1-indexed) is
   * `baseDelay * 2^(n - 1)`. Must be a non-negative number.
   * Defaults to `1000` (1 second).
   */
  baseDelay?: number;
  /**
   * Free-form metadata persisted on the job record. Returned by
   * the handler via `job.meta`. Useful for routing, tracing IDs,
   * user IDs, etc. Must be JSON-serialisable because it is logged
   * on every status transition.
   */
  meta?: Record<string, unknown>;
}

/**
 * The record the queue keeps about a single job. Stable for the
 * lifetime of the process unless the job is dropped (on completion)
 * or moved to the dead-letter array (on terminal failure).
 */
export interface Job<TPayload = unknown, TResult = unknown> {
  /** UUID v4 generated by `crypto.randomUUID()`. */
  readonly id: string;
  /** Job name; used to look up the worker in {@link JobQueue.onStart}. */
  readonly name: string;
  /** The opaque payload the worker will receive. */
  readonly payload: TPayload;
  /** Resolved options (with defaults applied). */
  readonly opts: Required<Pick<SubmitOptions, "maxAttempts" | "baseDelay">> & {
    meta: Record<string, unknown>;
  };
  /** Current lifecycle status. */
  status: JobStatus;
  /** Number of attempts so far. Incremented *before* a retry is scheduled. */
  attempts: number;
  /** `Date.now()` ms when the job was submitted. */
  readonly enqueuedAt: number;
  /** `Date.now()` ms when the worker started, or `undefined`. */
  startedAt?: number;
  /** `Date.now()` ms when the handler returned / threw terminally, or `undefined`. */
  completedAt?: number;
  /** Error message captured from the most recent failed attempt, if any. */
  lastError?: string;
  /** The handler's return value, captured on successful completion. */
  result?: TResult;
}

/**
 * What {@link JobQueue.submit} returns to the caller. The caller
 * does not need the full record up front — the id is enough to
 * correlate logs and look the job up later with
 * {@link JobQueue.getJob}.
 */
export interface SubmitResult {
  /** The newly assigned job id. */
  id: string;
  /** Always `"queued"` — the job is in the FIFO, waiting for a worker. */
  status: "queued";
}

/**
 * Worker signature. The handler receives the full job record so it
 * can read `payload`, `meta`, and (read-only) `attempts`. It can
 * return any value; on success the return value is stored on
 * `job.result` and forwarded to the `onComplete` hook. A throw or
 * rejected promise is treated as a failure and triggers the retry
 * / dead-letter logic.
 */
export type JobHandler<TPayload = unknown, TResult = unknown> = (
  job: Job<TPayload, TResult>,
) => Promise<TResult> | TResult;

/**
 * Hook signature. Both `onComplete` and `onFailure` are
 * fire-and-forget observers — they receive the job record and any
 * associated value (return value on complete, error on failure) and
 * are expected to return synchronously or via a `Promise`. Throws
 * are caught and logged so a misbehaving hook never breaks the
 * drain loop.
 */
export type JobHook<TPayload = unknown, TResult = unknown> = (
  job: Job<TPayload, TResult>,
  detail: { result?: TResult; error?: Error },
) => void | Promise<void>;

/**
 * Dead-letter record. Identical to a {@link Job} at the point of
 * death, plus a captured `deadAt` timestamp and the final error
 * normalised into an `Error` instance.
 */
export interface DeadLetter<TPayload = unknown, TResult = unknown> extends Job<TPayload, TResult> {
  /** `Date.now()` ms when the job was moved to the dead-letter array. */
  readonly deadAt: number;
  /** The final error that ended the retry loop. */
  readonly finalError: Error;
}

// ─── Internal defaults ─────────────────────────────────────────────────────

/** Default `maxAttempts` for jobs that do not override it. */
const DEFAULT_MAX_ATTEMPTS = 3;
/** Default `baseDelay` (ms) for jobs that do not override it. */
const DEFAULT_BASE_DELAY = 1000;
/** Default worker-pool size when none is supplied to the constructor. */
const DEFAULT_CONCURRENCY = 4;

// ─── JobQueue ──────────────────────────────────────────────────────────────

/**
 * In-memory FIFO job queue with a fixed-size worker pool, retry
 * with exponential backoff, dead-lettering, and lifecycle hooks.
 *
 * The class is intentionally framework-agnostic — it owns no
 * timers or I/O of its own beyond `setTimeout` for backoff. The
 * caller drives the lifecycle:
 *
 *   1. `new InMemoryJobQueue({ concurrency })` (or use the
 *      singleton from `@/lib/queue`).
 *   2. `queue.onStart("send-email", handler)` to register a worker
 *      for a job name.
 *   3. `queue.onComplete(hook)` / `queue.onFailure(hook)` to
 *      observe terminal events.
 *   4. `queue.submit("send-email", { to: "..." })` from anywhere
 *      in the process.
 *   5. `queue.processLoop()` to start draining. The loop never
 *      returns on its own — call `queue.close()` to stop it.
 *
 * Multiple workers can be registered for the same job name; the
 * most recent registration wins. This is intentional — it makes
 * hot-reload in development sane (the new module's `onStart`
 * overwrites the old one) without dragging in a "namespace"
 * concept.
 *
 * @typeParam TPayload Default payload type. Use the per-call
 *                     generics on {@link JobQueue.submit} to
 *                     narrow.
 * @typeParam TResult  Default result type. Same caveat as
 *                     `TPayload`.
 */
export class InMemoryJobQueue<TPayload = unknown, TResult = unknown> {
  /** FIFO of queued job ids. Workers consume from the head. */
  private readonly queue: string[] = [];
  /** All known jobs, keyed by id. Includes running, completed, and dead. */
  private readonly jobs = new Map<string, Job<TPayload, TResult>>();
  /** Workers, keyed by job name. */
  private readonly handlers = new Map<string, JobHandler<TPayload, TResult>>();
  /** `onComplete` hooks, fired in registration order. */
  private readonly completeHooks: JobHook<TPayload, TResult>[] = [];
  /** `onFailure` hooks, fired in registration order. */
  private readonly failureHooks: JobHook<TPayload, TResult>[] = [];
  /** Dead-letter array; jobs that exhausted their retry budget. */
  private readonly deadLetters: DeadLetter<TPayload, TResult>[] = [];
  /** Pending retry timers, keyed by job id. Cleared on `close()`. */
  private readonly retryTimers = new Map<string, NodeJS.Timeout>();
  /** Number of jobs currently executing. */
  private running = 0;
  /** Whether the drain loop should keep accepting new work. */
  private closed = false;
  /** Resolver for the `close()` promise; resolved when the loop is idle. */
  private idleResolver: (() => void) | null = null;
  /** Logger instance, captured at construction. */
  private readonly logger = getLogger().child({ module: "queue" });
  /** Metrics registry, captured at construction. */
  private readonly metrics = getMetrics();

  /** Configured worker pool size. */
  public readonly concurrency: number;

  /**
   * Build a new queue.
   *
   * @param options Optional configuration.
   * @param options.concurrency Number of jobs that may run in
   *                            parallel. Defaults to `4`. Capped at
   *                            `1` if a non-positive number is
   *                            supplied, because a zero-concurrency
   *                            queue would never drain.
   */
  constructor(options?: { concurrency?: number }) {
    const requested = options?.concurrency ?? DEFAULT_CONCURRENCY;
    this.concurrency = requested > 0 ? Math.floor(requested) : 1;
  }

  // ─── Public API ────────────────────────────────────────────────────────

  /**
   * Register a worker for `name`. Subsequent submissions of that
   * job name are routed here. The most recent registration wins —
   * see the class docstring for the rationale.
   *
   * The handler is invoked with the full job record. It may return
   * a value or a `Promise`. Throws (and rejections) are treated
   * as failures and trigger the retry loop.
   *
   * @param name    The job name to register for.
   * @param handler The worker function.
   * @returns The same queue, for chaining.
   *
   * @example
   * ```ts
   * queue.onStart("send-email", async (job) => {
   *   await sendEmail(job.payload as { to: string });
   *   return { delivered: true };
   * });
   * ```
   */
  public onStart(
    name: string,
    handler: JobHandler<TPayload, TResult>,
  ): this {
    this.handlers.set(name, handler);
    this.logger.debug({ jobName: name }, "worker registered");
    return this;
  }

  /**
   * Register a hook fired after every successful job. Hooks run in
   * registration order. A throw in a hook is caught and logged —
   * it will not break the drain loop or affect the job's
   * "completed" status.
   *
   * @param hook The callback to invoke.
   * @returns The same queue, for chaining.
   */
  public onComplete(hook: JobHook<TPayload, TResult>): this {
    this.completeHooks.push(hook);
    return this;
  }

  /**
   * Register a hook fired when a job is moved to the dead-letter
   * array. Fires *after* the job is in the dead-letter store, so
   * the hook can read it from {@link JobQueue.getDeadLetters}.
   * Same error-isolation contract as {@link onComplete}.
   *
   * @param hook The callback to invoke.
   * @returns The same queue, for chaining.
   */
  public onFailure(hook: JobHook<TPayload, TResult>): this {
    this.failureHooks.push(hook);
    return this;
  }

  /**
   * Enqueue a job. The job is assigned a UUID and pushed to the
   * tail of the FIFO. It will be picked up by a worker as soon as
   * one is idle.
   *
   * The function is synchronous because the underlying store is
   * in-memory. A future Redis-backed implementation would return
   * a `Promise<SubmitResult>` — keep callers off the sync API
   * surface when wiring that up.
   *
   * @param name    The job name. Must already have a registered
   *                handler, or the job will be dead-lettered
   *                immediately by the drain loop. Registering
   *                *after* submission is supported but means the
   *                job sits in `queued` until the registration
   *                arrives.
   * @param payload The job payload. Must be JSON-serialisable
   *                because it is logged on status transitions.
   * @param opts    Per-job overrides for `maxAttempts`,
   *                `baseDelay`, and `meta`.
   * @returns The new job's id and its initial status.
   */
  public submit(
    name: string,
    payload: TPayload,
    opts: SubmitOptions = {},
  ): SubmitResult {
    const id = crypto.randomUUID();
    const job: Job<TPayload, TResult> = {
      id,
      name,
      payload,
      opts: {
        maxAttempts:
          typeof opts.maxAttempts === "number" && opts.maxAttempts > 0
            ? Math.floor(opts.maxAttempts)
            : DEFAULT_MAX_ATTEMPTS,
        baseDelay:
          typeof opts.baseDelay === "number" && opts.baseDelay >= 0
            ? opts.baseDelay
            : DEFAULT_BASE_DELAY,
        meta: opts.meta ?? {},
      },
      status: "queued",
      attempts: 0,
      enqueuedAt: Date.now(),
    };
    this.jobs.set(id, job);
    this.queue.push(id);
    this.metrics.counter("queue_submitted_total", 1, { name });
    this.logger.info(
      { jobId: id, jobName: name, meta: job.opts.meta },
      "job submitted",
    );
    return { id, status: "queued" };
  }

  /**
   * Drain the queue. The function returns a `Promise` that
   * resolves only when {@link close} is called *and* every in-flight
   * job has finished. The loop ticks on the microtask queue, so
   * pending retries (handled via `setTimeout`) are awaited
   * naturally.
   *
   * The loop is single-threaded in JavaScript — it walks the FIFO
   * and starts workers up to the configured concurrency, then
   * yields. New submissions that arrive while the loop is
   * running are picked up on the next tick.
   *
   * Safe to call exactly once per `JobQueue` instance. A second
   * call is a no-op (logged at `warn`).
   */
  public async processLoop(): Promise<void> {
    if (this.closed) {
      this.logger.warn("processLoop called on a closed queue");
      return;
    }
    this.logger.info(
      { concurrency: this.concurrency },
      "queue drain loop started",
    );
    while (!this.closed || this.queue.length > 0 || this.running > 0) {
      // Fill the worker pool.
      while (
        this.running < this.concurrency &&
        this.queue.length > 0 &&
        !this.closed
      ) {
        const nextId = this.queue.shift();
        if (nextId === undefined) break;
        // Fire and forget — the worker's own promise chain is
        // tracked through `this.running`.
        void this.runJob(nextId);
      }
      // Yield to the event loop. `setImmediate` would be cheaper
      // but does not exist on the `lib: ["dom"]` side; `setTimeout`
      // with 0 is the cross-platform equivalent. Using a resolved
      // promise is equivalent in cost and reads more naturally.
      await Promise.resolve();
    }
    this.logger.info("queue drain loop exited cleanly");
  }

  /**
   * Stop accepting new work and wait for the queue to drain. Sets
   * the `closed` flag (no new jobs will start, but already-queued
   * jobs will still run) and resolves once `running === 0` and
   * the FIFO is empty. Pending retry timers are cancelled.
   *
   * Idempotent: calling `close()` twice is safe; the second call
   * is a no-op.
   *
   * @returns A promise that resolves when the queue is idle.
   */
  public async close(): Promise<void> {
    if (this.closed) return;
    this.logger.info("queue close requested");
    this.closed = true;
    // Cancel pending retries — those jobs will not run again
    // unless re-submitted. Materialise the entries first because
    // we mutate the map while iterating.
    for (const [id, timer] of Array.from(this.retryTimers)) {
      clearTimeout(timer);
      this.retryTimers.delete(id);
      this.logger.warn(
        { jobId: id },
        "pending retry cancelled by close()",
      );
    }
    if (this.running === 0 && this.queue.length === 0) return;
    await new Promise<void>((resolve) => {
      this.idleResolver = resolve;
    });
  }

  /**
   * Look up a job by id. Returns `null` if the id is unknown
   * (e.g. the job was never submitted, or the process was
   * restarted — the store is in-memory only).
   *
   * @param id The job id returned by {@link submit}.
   * @returns A reference to the live job record, or `null`.
   */
  public getJob(id: string): Job<TPayload, TResult> | null {
    return this.jobs.get(id) ?? null;
  }

  /**
   * Return a read-only snapshot of the dead-letter array. The
   * returned array is a *copy*; mutating it does not affect the
   * queue. The order is insertion order (oldest dead-letter
   * first).
   *
   * @returns A fresh array of dead-letter records.
   */
  public getDeadLetters(): DeadLetter<TPayload, TResult>[] {
    return [...this.deadLetters];
  }

  /**
   * Remove a job from the live store. Useful for tests; production
   * code should not need this — the queue manages its own
   * retention. Has no effect on the dead-letter array; use
   * {@link clearDeadLetters} for that.
   *
   * @param id The job id to drop.
   * @returns `true` if the job existed, `false` otherwise.
   */
  public forget(id: string): boolean {
    return this.jobs.delete(id);
  }

  /**
   * Clear the dead-letter array. Returns the number of records
   * that were removed. Primarily a test helper; admin tooling
   * could expose it behind a feature flag.
   *
   * @returns The number of dead-letter records that were dropped.
   */
  public clearDeadLetters(): number {
    const n = this.deadLetters.length;
    this.deadLetters.length = 0;
    return n;
  }

  /**
   * Number of jobs waiting in the FIFO. Cheap O(1) read.
   */
  public get pending(): number {
    return this.queue.length;
  }

  /**
   * Number of jobs currently executing on a worker. Cheap O(1)
   * read.
   */
  public get active(): number {
    return this.running;
  }

  /**
   * Number of jobs in the dead-letter array. Cheap O(1) read.
   */
  public get deadCount(): number {
    return this.deadLetters.length;
  }

  // ─── Internals ─────────────────────────────────────────────────────────

  /**
   * Execute one job. Pops the id, resolves the job record, runs
   * the registered handler, and routes the outcome (success vs
   * failure) to the right path. Errors thrown by the handler are
   * caught and turned into retry / dead-letter events.
   *
   * @param id The job id to run.
   */
  private async runJob(id: string): Promise<void> {
    const job = this.jobs.get(id);
    if (!job) {
      // Should not happen — `queue.shift()` returned an id we
      // don't know about. Log and move on.
      this.logger.error({ jobId: id }, "runJob: unknown id");
      return;
    }
    const handler = this.handlers.get(job.name);
    if (!handler) {
      // No worker registered. Dead-letter immediately so the job
      // does not sit in the queue forever. This is a programming
      // error in the caller; the failure hook still fires so it
      // is observable.
      const err = new Error(
        `No handler registered for job name "${job.name}"`,
      );
      this.metrics.counter("queue_deadletter_total", 1, {
        name: job.name,
        reason: "no_handler",
      });
      this.deadLetter(job, err);
      return;
    }

    job.attempts += 1;
    job.status = "running";
    job.startedAt = Date.now();
    this.running += 1;
    this.metrics.counter("queue_attempts_total", 1, { name: job.name });
    this.logger.info(
      {
        jobId: id,
        jobName: job.name,
        attempt: job.attempts,
        maxAttempts: job.opts.maxAttempts,
      },
      "job started",
    );

    const start = Date.now();
    try {
      const value = await handler(job);
      job.status = "completed";
      job.completedAt = Date.now();
      job.result = value as TResult;
      this.metrics.histogram(
        "queue_duration_ms",
        job.completedAt - start,
        { name: job.name, outcome: "success" },
      );
      this.metrics.counter("queue_completed_total", 1, { name: job.name });
      this.logger.info(
        {
          jobId: id,
          jobName: job.name,
          attempt: job.attempts,
          durationMs: job.completedAt - start,
        },
        "job completed",
      );
      await this.fireComplete(job, value as TResult);
    } catch (err) {
      const e = err instanceof Error ? err : new Error(String(err));
      job.lastError = e.message;
      this.metrics.histogram(
        "queue_duration_ms",
        Date.now() - start,
        { name: job.name, outcome: "error" },
      );
      this.logger.warn(
        {
          jobId: id,
          jobName: job.name,
          attempt: job.attempts,
          maxAttempts: job.opts.maxAttempts,
          err: e,
        },
        "job attempt failed",
      );
      if (job.attempts >= job.opts.maxAttempts) {
        this.metrics.counter("queue_deadletter_total", 1, {
          name: job.name,
          reason: "max_attempts",
        });
        this.deadLetter(job, e);
      } else {
        this.scheduleRetry(job, e);
      }
    } finally {
      this.running -= 1;
      if (this.closed && this.running === 0 && this.queue.length === 0) {
        this.idleResolver?.();
        this.idleResolver = null;
      }
    }
  }

  /**
   * Move a job to the dead-letter array and notify failure hooks.
   * The job is *not* removed from the live store — a future
   * {@link getJob} still returns it with `status === "dead"`, so
   * callers can correlate the original submission with the
   * dead-letter snapshot.
   *
   * @param job The job that exhausted its retries.
   * @param err The final error.
   */
  private deadLetter(job: Job<TPayload, TResult>, err: Error): void {
    job.status = "dead";
    job.completedAt = Date.now();
    job.lastError = err.message;
    const record: DeadLetter<TPayload, TResult> = {
      ...job,
      deadAt: Date.now(),
      finalError: err,
    };
    this.deadLetters.push(record);
    this.logger.error(
      {
        jobId: job.id,
        jobName: job.name,
        attempts: job.attempts,
        err,
      },
      "job moved to dead-letter",
    );
    void this.fireFailure(job, err);
  }

  /**
   * Schedule a retry with exponential backoff. The job's status
   * flips to `"failed"` (intermediate marker) and the id is
   * pushed back to the FIFO once the timer fires. The timer
   * handle is tracked so {@link close} can cancel it.
   *
   * @param job The job to retry.
   * @param _err The error from the failed attempt. Currently unused;
   *             kept in the signature for future logging.
   */
  private scheduleRetry(job: Job<TPayload, TResult>, _err: Error): void {
    job.status = "failed";
    // Exponential backoff: baseDelay * 2^(attempts - 1).
    // attempts is already incremented, so the first retry sees
    // attempts=1 → baseDelay * 2^0 = baseDelay. The second sees
    // attempts=2 → baseDelay * 2^1 = 2 * baseDelay. Etc.
    const exp = job.attempts - 1;
    const delay = job.opts.baseDelay * Math.pow(2, exp);
    this.metrics.histogram("queue_retry_delay_ms", delay, {
      name: job.name,
      attempt: String(job.attempts),
    });
    this.logger.info(
      {
        jobId: job.id,
        jobName: job.name,
        attempt: job.attempts,
        delayMs: delay,
      },
      "scheduling retry",
    );
    const timer = setTimeout(() => {
      this.retryTimers.delete(job.id);
      // Re-enqueue unless the queue was closed while we were
      // waiting. Closing the queue cancels retries explicitly
      // (see `close`), so reaching this point implies the queue
      // is still open.
      job.status = "queued";
      this.queue.push(job.id);
    }, delay);
    // Don't keep the Node process alive just for a retry timer —
    // a shutdown signal should drain immediately, not wait.
    if (typeof timer.unref === "function") timer.unref();
    this.retryTimers.set(job.id, timer);
  }

  /**
   * Fire every registered `onComplete` hook. Hooks are awaited
   * sequentially so a slow hook naturally serialises completion
   * notifications; an isolated throw is caught and logged.
   *
   * @param job    The job that just completed.
   * @param result The handler's return value.
   */
  private async fireComplete(
    job: Job<TPayload, TResult>,
    result: TResult,
  ): Promise<void> {
    for (const hook of this.completeHooks) {
      try {
        await hook(job, { result });
      } catch (err) {
        this.logger.error(
          {
            jobId: job.id,
            jobName: job.name,
            err: err instanceof Error ? err : new Error(String(err)),
          },
          "onComplete hook threw",
        );
      }
    }
  }

  /**
   * Fire every registered `onFailure` hook. Same isolation
   * contract as {@link fireComplete}.
   *
   * @param job The dead-lettered job.
   * @param err The final error.
   */
  private async fireFailure(
    job: Job<TPayload, TResult>,
    err: Error,
  ): Promise<void> {
    for (const hook of this.failureHooks) {
      try {
        await hook(job, { error: err });
      } catch (hookErr) {
        this.logger.error(
          {
            jobId: job.id,
            jobName: job.name,
            err:
              hookErr instanceof Error
                ? hookErr
                : new Error(String(hookErr)),
          },
          "onFailure hook threw",
        );
      }
    }
  }
}

/**
 * Type alias re-exported so consumers can write
 * `JobQueue<MyPayload>` instead of the more verbose
 * `InMemoryJobQueue<MyPayload>`. Identical shape.
 *
 * @typeParam TPayload Default payload type.
 * @typeParam TResult  Default result type.
 */
export type JobQueue<TPayload = unknown, TResult = unknown> = InMemoryJobQueue<
  TPayload,
  TResult
>;
